import type { Metadata } from "next";
// Supports weights 100-900
import '@fontsource-variable/montserrat';
import "./globals.css";
import { Toast } from "@/module/common/components/toast";
import { LayoutClient } from "./layoutClient";
import { createClient } from "@/supabase/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const client = await createClient()

  const user = await client.auth.getUser()

  return (
    <html lang="en">
      <body
        className="bg-base-100"
        data-theme="lofi"
      >
        <LayoutClient
          user={user.data.user}
        >
          <Toast />
          {children}
        </LayoutClient>
      </body>
    </html>
  );
}
